#!/bin/sh
#
# Retroflag GPI CASE 2 - Autosave script. 
# This script will save the current game (RetroArch) every 300 seconds (5 minutes).
# So no more accidential loss of the game state. ;-)
#
# 
# INSTALLATION
# 1. 	connect with ssh to your recallbox (ip can befound in the main menu -> network settings) e.g. ssh root@192.168.1.10
# 		default password: recalboxroot 
#
#	2. 	remount filesystem for writing:
#			mount -o remount, rw /
#
# 3. 	create new file
#			vim /etc/init.d/S99_custom_autosave_300s
#
#	4.	insert the whole content of this file
#
# 5.	save and exit file
#
# 6. 	make file executable
#			chmod 755 /etc/init.d/S99_custom_autosave_300s
#
# 7. 	ENJOY! ;-)
#

start() {
	while true; do

		process_name="retroarch"

		# check if retroarch is running
		if pgrep -x "$process_name" >/dev/null; then
			# retroarch process exists so do save

			# increase save slot
			echo -n "STATE_SLOT_PLUS" > /dev/udp/127.0.0.1/55355
			sleep 1 # let emulator some time

			# explicitly save game (not needed if "savestate_auto_save = true" in your config)
			echo -n "SAVE_STATE" > /dev/udp/127.0.0.1/55355
		fi

		sleep 300 # wait 5 Minutes till next save
	done &
}

stop() {	# will be executed when the system shuts down
	true; ## This can be removed if something else should happen when recallbox shuts down. (true is just a placeholder)
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
